# Project 3
----

### Summary
This notebook shows the process we followed to clean, explore and analyze the data set 
that contains information about the __Food Prices__. Also, contains the variables of interest for the project. 

However to make the final visualizations, we included only a small set of these variables.

----

In [1]:
# Dependencies
import pandas as pd

In [10]:
# Use Pandas to read data
food_df = pd.read_csv("./Resources/Prices_E_Americas.csv", encoding="ISO-8859-1", low_memory=False) 

# Show the number of records
food_df.count()

Area Code       5376
Area            5376
Item Code       5376
Item            5376
Element Code    5376
Element         5376
Unit            5376
Y1991           3033
Y1991F           210
Y1992           3192
Y1992F           318
Y1993           3315
Y1993F           420
Y1994           3387
Y1994F           462
Y1995           3576
Y1995F           496
Y1996           3787
Y1996F           523
Y1997           3847
Y1997F           502
Y1998           3946
Y1998F           508
Y1999           4032
Y1999F           490
Y2000           4110
Y2000F           463
Y2001           4122
Y2001F           487
Y2002           4077
                ...
Y2003           4119
Y2003F           373
Y2004           3840
Y2004F           613
Y2005           3885
Y2005F           586
Y2006           3870
Y2006F           553
Y2007           3945
Y2007F           574
Y2008           4049
Y2008F           697
Y2009           3710
Y2009F           562
Y2010           3857
Y2010F           463
Y2011           3848
Y2011F           469
Y2012           3874
Y2012F           406
Y2013           3772
Y2013F           364
Y2014           3625
Y2014F           286
Y2015           3339
Y2015F           226
Y2016           2967
Y2016F           147
Y2017           2149
Y2017F             0
Length: 61, dtype: int64

In [11]:
# Show the results
food_df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y1991,Y1991F,Y1992,...,Y2013,Y2013F,Y2014,Y2014F,Y2015,Y2015F,Y2016,Y2016F,Y2017,Y2017F
0,8,Antigua and Barbuda,486,Bananas,5530,Producer Price (LCU/tonne),LCU,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8,Antigua and Barbuda,486,Bananas,5531,Producer Price (SLC/tonne),SLC,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8,Antigua and Barbuda,486,Bananas,5532,Producer Price (USD/tonne),USD,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8,Antigua and Barbuda,414,"Beans, green",5530,Producer Price (LCU/tonne),LCU,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8,Antigua and Barbuda,414,"Beans, green",5531,Producer Price (SLC/tonne),SLC,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
food_df.dtypes

Area Code         int64
Area             object
Item Code         int64
Item             object
Element Code      int64
Element          object
Unit             object
Y1991           float64
Y1991F           object
Y1992           float64
Y1992F           object
Y1993           float64
Y1993F           object
Y1994           float64
Y1994F           object
Y1995           float64
Y1995F           object
Y1996           float64
Y1996F           object
Y1997           float64
Y1997F           object
Y1998           float64
Y1998F           object
Y1999           float64
Y1999F           object
Y2000           float64
Y2000F           object
Y2001           float64
Y2001F           object
Y2002           float64
                 ...
Y2003           float64
Y2003F           object
Y2004           float64
Y2004F           object
Y2005           float64
Y2005F           object
Y2006           float64
Y2006F           object
Y2007           float64
Y2007F           object
Y2008           float64
Y2008F           object
Y2009           float64
Y2009F           object
Y2010           float64
Y2010F           object
Y2011           float64
Y2011F           object
Y2012           float64
Y2012F           object
Y2013           float64
Y2013F           object
Y2014           float64
Y2014F           object
Y2015           float64
Y2015F           object
Y2016           float64
Y2016F           object
Y2017           float64
Y2017F          float64
Length: 61, dtype: object

In [23]:
mex_df = food_df.loc[(food_df["Area"] == 'Mexico') & (food_df["Unit"] == 'USD')]
#LCU - Local Currency Unit
mex_df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y1991,Y1991F,Y1992,...,Y2013,Y2013F,Y2014,Y2014F,Y2015,Y2015F,Y2016,Y2016F,Y2017,Y2017F
2858,138,Mexico,800,Agave fibres nes,5532,Producer Price (USD/tonne),USD,82.8,NaN,84.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2861,138,Mexico,711,"Anise, badian, fennel, coriander",5532,Producer Price (USD/tonne),USD,882.2,NaN,1909.3,...,2038.5,NaN,1669.9,NaN,1628.7,NaN,1147.7,NaN,1170.5,NaN
2864,138,Mexico,515,Apples,5532,Producer Price (USD/tonne),USD,403.9,NaN,287.2,...,389.0,NaN,441.3,NaN,363.5,NaN,348.2,NaN,461.0,NaN
2867,138,Mexico,526,Apricots,5532,Producer Price (USD/tonne),USD,NaN,NaN,NaN,...,905.7,F,834.2,F,405.1,NaN,340.7,NaN,323.9,NaN
2870,138,Mexico,366,Artichokes,5532,Producer Price (USD/tonne),USD,988.3,NaN,965.8,...,681.0,NaN,847.5,NaN,449.6,NaN,467.6,NaN,542.0,NaN

In [29]:
# Verify that there are not more missing values
percent_missing = mex_df.isnull().sum() * 100 / len(mex_df)
missing_value_df = pd.DataFrame({'percent_missing': percent_missing})
missing_value_df.sort_values('percent_missing', inplace=True, ascending=False)
missing_value_df

              percent_missing
Y2017F             100.000000
Y1991F             100.000000
Y1996F              98.496241
Y1992F              98.496241
Y1994F              97.744361
Y2016F              97.744361
Y2015F              97.744361
Y2000F              97.744361
Y1998F              97.744361
Y1999F              96.992481
Y1997F              96.992481
Y2002F              96.992481
Y1993F              96.240602
Y2001F              96.240602
Y2014F              96.240602
Y1995F              96.240602
Y2013F              95.488722
Y2012F              95.488722
Y2010F              95.488722
Y2011F              94.736842
Y2007F              93.984962
Y2006F              93.984962
Y2003F              93.984962
Y2008F              93.233083
Y2004F              93.233083
Y2005F              93.233083
Y2009F              91.729323
Y2017               18.796992
Y1991               16.541353
Y2016               15.789474
...                       ...
Y2015               12.030075
Y1993               12.030075
Y1994               12.030075
Y2014               11.278195
Y2010               11.278195
Y2007               11.278195
Y2009               11.278195
Y2006               11.278195
Y2008               11.278195
Y2004               10.526316
Y2005               10.526316
Y2013               10.526316
Y1995               10.526316
Y2011               10.526316
Y1997                9.774436
Y2012                9.022556
Y1996                9.022556
Y1998                8.270677
Y1999                5.263158
Y2001                5.263158
Y2002                5.263158
Y2000                5.263158
Y2003                4.511278
Item                 0.000000
Item Code            0.000000
Element Code         0.000000
Unit                 0.000000
Element              0.000000
Area                 0.000000
Area Code            0.000000

[61 rows x 1 columns]

In [24]:
can_df = food_df.loc[(food_df["Area"] == 'Canada') & (food_df["Unit"] == 'USD')]
can_df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y1991,Y1991F,Y1992,...,Y2013,Y2013F,Y2014,Y2014F,Y2015,Y2015F,Y2016,Y2016F,Y2017,Y2017F
992,33,Canada,515,Apples,5532,Producer Price (USD/tonne),USD,247.0,NaN,221.7,...,553.0,NaN,475.2,NaN,414.8,NaN,429.4,NaN,471.8,NaN
995,33,Canada,526,Apricots,5532,Producer Price (USD/tonne),USD,807.4,NaN,614.7,...,1657.1,NaN,1317.0,NaN,1328.9,NaN,1426.6,NaN,1459.1,NaN
998,33,Canada,367,Asparagus,5532,Producer Price (USD/tonne),USD,1840.8,NaN,1981.4,...,3479.0,NaN,3425.4,NaN,3133.3,NaN,3105.6,NaN,3516.5,NaN
1001,33,Canada,44,Barley,5532,Producer Price (USD/tonne),USD,64.6,NaN,62.9,...,237.3,NaN,169.0,NaN,174.1,NaN,166.3,NaN,148.8,NaN
1004,33,Canada,176,"Beans, dry",5532,Producer Price (USD/tonne),USD,255.7,NaN,285.4,...,817.5,NaN,793.6,NaN,726.4,NaN,656.7,NaN,622.5,NaN

In [ ]:
percent_missing = can_df.isnull().sum() * 100 / len(can_df)
missing_value_df = pd.DataFrame({'percent_missing': percent_missing})
missing_value_df.sort_values('percent_missing', inplace=True, ascending=False)
missing_value_df

In [25]:
usa_df = food_df.loc[(food_df["Area"] == 'United States of America') & (food_df["Unit"] == 'USD')]
usa_df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y1991,Y1991F,Y1992,...,Y2013,Y2013F,Y2014,Y2014F,Y2015,Y2015F,Y2016,Y2016F,Y2017,Y2017F
4679,231,United States of America,221,"Almonds, with shell",5532,Producer Price (USD/tonne),USD,1571.0,NaN,1716.0,...,7077.0,NaN,8818.0,NaN,6900.0,NaN,5379.0,NaN,NaN,NaN
4682,231,United States of America,515,Apples,5532,Producer Price (USD/tonne),USD,395.0,NaN,300.0,...,668.0,NaN,567.0,NaN,741.0,NaN,705.0,NaN,NaN,NaN
4685,231,United States of America,526,Apricots,5532,Producer Price (USD/tonne),USD,407.0,NaN,356.0,...,812.0,NaN,902.0,NaN,1113.0,NaN,990.0,NaN,NaN,NaN
4688,231,United States of America,226,Areca nuts,5532,Producer Price (USD/tonne),USD,NaN,NaN,NaN,...,1918.0,NaN,1918.0,NaN,2138.0,NaN,2205.0,NaN,NaN,NaN
4691,231,United States of America,366,Artichokes,5532,Producer Price (USD/tonne),USD,NaN,NaN,869.0,...,1345.0,NaN,1270.0,NaN,1936.0,NaN,1737.0,NaN,1543.0,NaN

In [ ]:
percent_missing = usa_df.isnull().sum() * 100 / len(usa_df)
missing_value_df = pd.DataFrame({'percent_missing': percent_missing})
missing_value_df.sort_values('percent_missing', inplace=True, ascending=False)
missing_value_df

In [26]:
# Count the rows by country
mex_df.groupby('Area')['Item'].value_counts()

Area    Item
Mexico  Agave fibres nes                                1
        Anise, badian, fennel, coriander                1
        Apples                                          1
        Apricots                                        1
        Artichokes                                      1
        Asparagus                                       1
        Avocados                                        1
        Bananas                                         1
        Bananas non-Cavendish                           1
        Barley                                          1
        Beans, dry                                      1
        Beans, green                                    1
        Beeswax                                         1
        Berries nes                                     1
        Blueberries                                     1
        Broad beans, horse beans, dry                   1
        Cabbages and other brassicas                    1
        Canary seed                                     1
        Carobs                                          1
        Carrots and turnips                             1
        Cashew nuts, with shell                         1
        Cassava                                         1
        Castor oil seed                                 1
        Cauliflowers and broccoli                       1
        Cherries                                        1
        Chestnut                                        1
        Chick peas                                      1
        Chillies and peppers, dry                       1
        Chillies and peppers, green                     1
        Cocoa, beans                                    1
                                                       ..
        Roots and tubers, nes                           1
        Rubber, natural                                 1
        Rye                                             1
        Safflower seed                                  1
        Seed cotton                                     1
        Sesame seed                                     1
        Sisal                                           1
        Sorghum                                         1
        Soybeans                                        1
        Spinach                                         1
        Strawberries                                    1
        String beans                                    1
        Sugar beet                                      1
        Sugar cane                                      1
        Sunflower seed                                  1
        Sweet potatoes                                  1
        Tangerines, mandarins, clementines, satsumas    1
        Tea                                             1
        Tobacco, unmanufactured                         1
        Tomatoes                                        1
        Triticale                                       1
        Vanilla                                         1
        Vegetables, fresh nes                           1
        Vegetables, leguminous nes                      1
        Vetches                                         1
        Walnuts, with shell                             1
        Watermelons                                     1
        Wheat                                           1
        Wool, greasy                                    1
        Yautia (cocoyam)                                1
Name: Item, Length: 133, dtype: int64

In [30]:
# Get information for the graph - totals by variable
mex_df.groupby(['Item']).agg({i:'value_counts' for i in mex_df.columns[9:102]})

,,Y1992,Y1992F,Y1993,Y1993F,Y1994,Y1994F,Y1995,Y1995F,Y1996,Y1996F,...,Y2013,Y2013F,Y2014,Y2014F,Y2015,Y2015F,Y2016,Y2016F,Y2017,Y2017F
Agave fibres nes,84.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Anise, badian, fennel, coriander",1909.3,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Apples,287.2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Artichokes,965.8,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Asparagus,2297.3,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Avocados,602.6,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bananas,186.4,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Barley,224.6,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Beans, dry",732.2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Beans, green",370.3,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Beeswax,1375.5,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Berries nes,908.6,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Broad beans, horse beans, dry",529.6,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cabbages and other brassicas,157.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Canary seed,247.2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Carobs,747.7,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Carrots and turnips,162.2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Cashew nuts, with shell",430.8,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cassava,290.5,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Castor oil seed,290.8,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cauliflowers and broccoli,258.2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cherries,1420.7,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Chick peas,518.9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Chillies and peppers, green",557.7,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Cocoa, beans",921.5,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Coconuts,236.8,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Coffee, green",191.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cucumbers and gherkins,304.7,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dates,1908.9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Eggplants (aubergines),705.4,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Pumpkins, squash and gourds",404.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Quinces,511.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Rapeseed,365.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Raspberries,1976.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
"Rice, paddy",217.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
"Rubber, natural",728.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Rye,181.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Safflower seed,295.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Seed cotton,647.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Sesame seed,850.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Sorghum,166.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Soybeans,370.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Spinach,259.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Strawberries,1014.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Sugar cane,35.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Sunflower seed,289.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Sweet potatoes,227.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
"Tangerines, mandarins, clementines, satsumas",125.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Tea,72.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
"Tobacco, unmanufactured",1717.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Tomatoes,388.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Triticale,182.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Vanilla,5476.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
"Vegetables, leguminous nes",277.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Vetches,44.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
"Walnuts, with shell",4094.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Watermelons,183.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Wheat,200.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
"Wool, greasy",269.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
Yautia (cocoyam),242.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN